#Expyriment 1.0.0 (Python 3.13.7), .xpe-file, coding: cp1252
#date: Wed Sep 24 2025 16:14:43
#sha1: d0ff4c
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='DESKTOP-GNBUSH4', release='11', version='10.0.26100', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
803,stderr,received,'Exception ignored in: <function Visual.__del__ at 0x00000244E95CE980>'
803,stderr,received,'Traceback (most recent call last):'
803,stderr,received,'  File "C:\\Users\\lucie\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\expyriment\\stimuli\\_visual.py", line 266, in __del__'
834,stderr,received,'    if self._compression_filename is not None:'
834,stderr,received,"AttributeError: 'Shape' object has no attribute '_compression_filename'"
835,stderr,received,'Traceback (most recent call last):'
835,stderr,received,'  File "C:\\Users\\lucie\\documents\\CogSup\\Programming\\Assignments\\Week-2\\Exercises\\labeled_shapes.py", line 12, in <module>\n    triangle = stimuli.Shape(vertices_triangle=[(50,50)], colour = (225,0,225), position = (-125, 0))'
835,stderr,received,"TypeError: Shape.__init__() got an unexpected keyword argument 'vertices_triangle'"
