#Expyriment 1.0.0 (Python 3.13.7), .xpe-file, coding: cp1252
#date: Mon Sep 29 2025 14:58:18
#sha1: 327d9f
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='DESKTOP-GNBUSH4', release='11', version='10.0.26100', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
738,stderr,received,'Exception ignored in: <function Visual.__del__ at 0x000002539122EA20>'
738,stderr,received,'Traceback (most recent call last):'
738,stderr,received,'  File "C:\\Users\\lucie\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\expyriment\\stimuli\\_visual.py", line 266, in __del__'
753,stderr,received,'    if self._compression_filename is not None:'
753,stderr,received,"AttributeError: 'Circle' object has no attribute '_compression_filename'"
754,stderr,received,'Traceback (most recent call last):'
754,stderr,received,'  File "C:\\Users\\lucie\\Documents\\CogSup\\Programming\\Assignments\\Week-3\\Exercises\\kanizsa-square.py", line 19, in <module>\n    circle1 = stimuli.Circle(size=(c_size,c_size), colour=(colour.C_BLACK), position=(-width//4,height//4))'
754,stderr,received,"TypeError: Circle.__init__() got an unexpected keyword argument 'size'"
